# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --save-dev @electron-forge/cli
    - run: npx electron-forge import
    - run: npm run make
    - run: ls out
    - name: Archive compilation output
      uses: actions/upload-artifact@v2
      with:
          name: release-ubuntu
          path: out/roseplayer-linux-x64
          
  build-windows:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --save-dev @electron-forge/cli
    - run: npx electron-forge import
    - run: npm run make
    - run: ls out
    - name: Archive compilation output
      uses: actions/upload-artifact@v2
      with:
          name: release-windows
          path: out/roseplayer-win32-x64          
          
          
          
